Repository car-ffeine/admin, pull requests merged in 2023-08, with the labels that each got.

#3 feat: 재사용 가능한 표 컴포넌트를 구현한다
  .githooks/commit-msg
  .github/workflows/deploy.yml
  .github/workflows/storybook.yml
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/preview.tsx
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.tsx
  src/common.css
  src/components/Table/AdminTable.stories.tsx
  src/components/Table/AdminTable.tsx
  src/components/Table/AdminTableBody.tsx
  src/components/Table/AdminTableHead.stories.tsx
  src/components/Table/AdminTableHead.tsx
  src/components/Table/AdminTablePagination.stories.tsx
  src/components/Table/AdminTablePagination.tsx
  src/components/Table/index.ts
  src/constants/index.ts
  src/mocks/index.ts
  src/types/index.ts
  src/utils/external-state/StateManager.ts
  src/utils/external-state/index.ts
  src/utils/external-state/tools.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: feat, chore

#5 chore: PR 머지됐을 때 자동으로 관련 issue close하는 기능을 구현한다
  .github/workflows/link_pr_to_issue.yml
Labels: chore

#9 feat: Admin 페이지의 모달 컴포넌트를 구현한다
  .github/workflows/link_pr_to_issue.yml
  src/App.tsx
  src/common/Modal/Modal.stories.tsx
  src/common/Modal/Modal.tsx
  src/common/Modal/index.ts
  src/components/ModalContainer.tsx
  src/components/Table/AdminTable.tsx
  src/components/Table/AdminTableBody.tsx
  src/components/Table/AdminTableHead.stories.tsx
  src/components/Table/AdminTableHead.tsx
  src/stores/modalStateStore.ts
  tsconfig.json
Labels: feat

#12 feat: 모달에 들어갈 폼 컴포넌트를 구현한다
  src/App.tsx
  src/common.css
  src/common/Modal/Modal.stories.tsx
  src/common/Modal/Modal.tsx
  src/common/Toast/Toast.stories.tsx
  src/common/Toast/Toast.tsx
  src/common/Toast/ToastContainer.tsx
  src/common/Toast/index.ts
  src/common/Toast/style/index.ts
  src/common/Toast/types/index.ts
  src/common/Toast/utils/calculateToastDuration.ts
  src/components/Form/Form.stories.tsx
  src/components/Form/Form.tsx
  src/components/Form/index.tsx
  src/components/ModalContainer.stories.tsx
  src/components/ModalContainer.tsx
  src/components/Table/AdminTableBody.tsx
  src/components/Table/AdminTableHead.tsx
  src/constants/index.ts
  src/mocks/index.ts
  src/stores/toastStore.ts
  src/styles/index.ts
  src/types/index.ts
  src/utils/getTypedObjectEntries.ts
  src/utils/getTypedObjectFromEntries.ts
  src/utils/getTypedObjectKeys.ts
  tsconfig.json
Labels: feat

#11 feat: Admin 페이지의 네비게이션을 구현한다
  .githooks/commit-msg
  Makefile
  src/App.tsx
  src/common.css
  src/components/Navigation/Navigation.stories.tsx
  src/components/Navigation/Navigation.tsx
  src/components/Navigation/NavigationContainer.tsx
  src/components/Navigation/NavigationMenu.stories.tsx
  src/components/Navigation/NavigationMenu.tsx
  src/components/Navigation/index.ts
  src/components/Table/AdminTable.tsx
  src/constants/index.ts
  src/types/index.ts
Labels: feat

#15 feat: 간편 로그인 컴포넌트를 구현한다
  .prettierrc
  .storybook/main.ts
  package-lock.json
  package.json
  src/assets/car-ffeine-logo.svg
  src/assets/car-ffeine-white-logo.svg
  src/assets/google-logo.svg
  src/common/Modal/Modal.stories.tsx
  src/common/Modal/Modal.tsx
  src/components/Form/Form.tsx
  src/components/Login/Login.stories.tsx
  src/components/Login/Login.tsx
  src/components/Login/index.ts
  src/components/ModalContainer.stories.tsx
  src/components/ModalContainer.tsx
  src/components/Navigation/Navigation.stories.tsx
  src/components/Navigation/Navigation.tsx
  src/components/Navigation/NavigationContainer.tsx
  src/components/Navigation/NavigationMenu.stories.tsx
  src/components/Navigation/NavigationMenu.tsx
  src/components/Table/AdminTableBody.tsx
  src/constants/index.ts
  src/stores/modalStateStore.ts
  src/types/index.ts
  src/vite-svg.d.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: feat

#17 feat: 간편 로그인 기능을 구현한다
  .prettierrc
  package-lock.json
  package.json
  src/App.tsx
  src/assets/car-ffeine-white-logo.svg
  src/assets/car-loading.svg
  src/components/Form/Form.tsx
  src/components/Login/Loading.stories.tsx
  src/components/Login/Loading.tsx
  src/components/Login/LoginModalContent.stories.tsx
  src/components/Login/LoginModalContent.tsx
  src/components/Login/LoginProcessing.tsx
  src/components/Login/index.ts
  src/components/Navigation/NavigationMenu.tsx
  src/constants/index.ts
  src/constants/login.ts
  src/constants/url.ts
  src/hooks/login/getLoginUri.ts
  src/hooks/login/getMemberToken.ts
  src/main.tsx
  src/router/index.tsx
  src/utils/storage.ts
  src/utils/typed-object/getTypedObjectEntries.ts
  src/utils/typed-object/getTypedObjectFromEntries.ts
  src/utils/typed-object/getTypedObjectKeys.ts
  tsconfig.json
  yarn.lock
Labels: feat

#19 fix: 배포 오류를 개선한다
  src/router/index.tsx
Labels: bug

#21 refactor: uri 변경한다
  src/constants/login.ts
Labels: refactor

#24 feat: 전체 충전소 페이지 데이터 요청하는 기능을 구현한다
  index.html
  package-lock.json
  package.json
  src/common.css
  src/common/Toast/Toast.stories.tsx
  src/components/Form/Form.tsx
  src/components/Login/LoginModalContent.tsx
  src/components/Login/LoginProcessing.tsx
  src/components/Navigation/NavigationMenu.tsx
  src/components/Table/AdminTable.tsx
  src/components/Table/AdminTableBody.tsx
  src/components/Table/AdminTablePagination.stories.tsx
  src/components/Table/AdminTablePagination.tsx
  src/constants/index.ts
  src/constants/url.ts
  src/hooks/login/getLoginUri.ts
  src/hooks/login/getMemberToken.ts
  src/hooks/login/useLoginUri.ts
  src/hooks/login/useMemberToken.ts
  src/hooks/stations/useFetchStations.ts
  src/stores/memberTokenStore.ts
  src/types/index.ts
  yarn.lock
Labels: feat

#27 feat: 전체 충전소 페이지에서 정보 수정 요청 보내는 기능 구현한다
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/Form/Form.stories.tsx
  src/components/Form/Form.tsx
  src/components/Table/AdminTable.tsx
  src/components/Table/AdminTableBody.tsx
  src/components/Table/ButtonContainer/ButtonContainer.stories.tsx
  src/components/Table/ButtonContainer/ButtonContainer.tsx
  src/components/Table/ButtonContainer/ButtonStyle.ts
  src/components/Table/ButtonContainer/DetailsButton/DetailsButton.tsx
  src/components/Table/ButtonContainer/DetailsButton/index.ts
  src/components/Table/ButtonContainer/EditButton/EditButton.tsx
  src/components/Table/ButtonContainer/EditButton/index.ts
  src/components/Table/ButtonContainer/index.ts
  src/hooks/stations/useFetchStations.ts
  src/hooks/stations/useRequestStationEdit.ts
  src/stores/stationSummaryListStore.ts
  src/types/index.ts
  yarn.lock
Labels: feat

#29 feat: 상세 버튼 클릭시 충전소의 상세 정보가 담긴 모달이 나오는 기능 구현한다
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/App.tsx
  src/assets/404-error.svg
  src/common/Error/Error.stories.tsx
  src/common/Error/Error.tsx
  src/common/Error/index.ts
  src/common/Loading/Loading.stories.tsx
  src/common/Loading/Loading.tsx
  src/common/Loading/index.ts
  src/common/Modal/Modal.tsx
  src/components/Form/Form.tsx
  src/components/Login/LoginModalContent.tsx
  src/components/Login/LoginProcessing.tsx
  src/components/ModalContainer.tsx
  src/components/Navigation/NavigationMenu.tsx
  src/components/StationDetails/ChargerCard.stories.tsx
  src/components/StationDetails/ChargerCard.tsx
  src/components/StationDetails/StationDetails.tsx
  src/components/StationDetails/index.ts
  src/components/Table/AdminTable.tsx
  src/components/Table/AdminTableHead.stories.tsx
  src/components/Table/ButtonContainer/ButtonContainer.tsx
  src/components/Table/ButtonContainer/DetailsButton/DetailsButton.tsx
  src/constants/index.ts
  src/constants/queryKeys.ts
  src/constants/url.ts
  src/hooks/stations/useFetchStationDetails.ts
  src/hooks/stations/useRequestStationEdit.ts
  src/main.tsx
  src/router/index.tsx
  src/stores/modalStateStore.ts
  src/types/index.ts
  yarn.lock
Labels: feat

#31 feat: 전체 충전소 수정 완료시 전체 충전소 페이지도 업데이트 되는 기능 구현한다
  .storybook/preview.tsx
  src/App.tsx
  src/common/Error/Error.tsx
  src/common/Modal/Modal.tsx
  src/common/Toast/Toast.tsx
  src/components/Form/Form.stories.tsx
  src/components/Form/Form.tsx
  src/components/StationDetails/StationDetails.tsx
  src/components/Table/AdminTable.stories.tsx
  src/components/Table/AdminTable.tsx
  src/constants/queryKeys.ts
  src/hooks/stations/useFetchStations.ts
  src/hooks/stations/useFetchStationsSummary.ts
  src/hooks/stations/useRequestStationEdit.ts
  src/main.tsx
  src/stores/pageStore.ts
Labels: feat

#33 feat: 페이지네이션 기능 구현한다
  src/App.tsx
  src/components/Table/AdminTable.tsx
  src/components/Table/AdminTablePagination.tsx
  src/hooks/stations/useFetchStationsSummary.ts
  src/main.tsx
Labels: feat

#37 fix: 셀렉트 박스가 작동하지 않는 에러 개선한다
  src/common/Modal/Modal.tsx
  src/common/Toast/Toast.tsx
  src/components/Navigation/Navigation.tsx
Labels: bug
